version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD} 
      POSTGRES_DB: ${TYPEORM_DB_NAME}
    container_name: training-db
    volumes:
      - ./postgres:/var/lib/postgresql/data